### ISSUE TITLE
crashes with the version provided on the curseforge page

### ISSUE THREAD

**Issue by PopcornHead51** [Yoghurt4C/BetterWithPatches#1]
[crash-2023-04-03_20.43.15-client.txt](https://github.com/Yoghurt4C/BetterWithPatches/files/11143625/crash-2023-04-03_20.43.15-client.txt)

**Comment by Yoghurt4C** [comment]
try this https://archive.org/details/better-with-mods-1.7.10-0.6.2-beta

**Comment by PopcornHead51** [comment]
oddly I still have the issue:
[crash-2023-04-04_19.26.34-client.txt](https://github.com/Yoghurt4C/BetterWithPatches/files/11153926/crash-2023-04-04_19.26.34-client.txt)

**Comment by PopcornHead51** [comment]
here's the log if it helps:
[latest.log](https://github.com/Yoghurt4C/BetterWithPatches/files/11153930/latest.log)

**Comment by Yoghurt4C** [comment]
the log actually helped, because it seems that the combination of really old java and my injecting an array initializer into a class makes it crash. can you try this version?
[betterwithpatches-0.6.4+HOMECOOKED.zip](https://github.com/Yoghurt4C/BetterWithPatches/files/11155794/betterwithpatches-0.6.4%2BHOMECOOKED.zip)
unzip it first because github doesn't allow uploading jars

**Comment by PopcornHead51** [comment]
this fixed the issue
